trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: 'test/DFEngine.Compilers.TSQL.UnitTests/DFEngine.Compilers.TSQL.UnitTests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/DFEngine.Compilers.TSQL/DFEngine.Compilers.TSQL.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '0'
    minorVersion: '2'
    patchVersion: '0'